<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="WebForm1.aspx.cs" Inherits="example02.WebForm1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <asp:GridView
            ID="GridView1"
            DataSourceID="SqlDataSource1"
            DataKeyNames="CustomerID"
            AutoGenerateDeleteButton="true"
            AutoGenerateColumns="false"
            AllowPaging="true"
            ShowFooter="true"
            runat="server">

            <Columns>
                <asp:TemplateField>
                    <ItemTemplate>
                       <asp:Label ID="CustomerIDLabel" runat="server">
                           <%# Eval("CustomerID") %>
                       </asp:Label>
                    </ItemTemplate>
                    <FooterTemplate>
                        <asp:TextBox ID="CustomerIDTextBox" runat="server"></asp:TextBox>
                    </FooterTemplate>
                </asp:TemplateField>

                 <asp:TemplateField>
                    <ItemTemplate>
                       <asp:Label ID="CompanyNameLabel" runat="server">
                           <%# Eval("CompanyName") %>
                       </asp:Label>
                    </ItemTemplate>
                    <FooterTemplate>
                        <asp:TextBox ID="CompanyNameTextBox" runat="server"></asp:TextBox>
                    </FooterTemplate>
                </asp:TemplateField>

                <asp:TemplateField>
                    <FooterTemplate>
                        <asp:DropDownList
                            ID="ContacTitleDropDownList1"
                            DataSourceID="SqlDataSource2"
                            DataTextField="ContactTitle"
                            DataValueField="ContactTitle"                            
                            AppendDataBoundItems="true"
                            runat="server">

                            <asp:ListItem Text="Selecciona el cargo"></asp:ListItem>

                        </asp:DropDownList>

                        <asp:SqlDataSource
                            ID="SqlDataSource2"
                            ConnectionString="<%$ ConnectionStrings:Northwind %>"
                            SelectCommand="select distinct ContactTitle from Customers"
                            runat="server">

                        </asp:SqlDataSource>

                        <asp:Button ID="Button1" runat="server" Text="Button" OnClick="Button1_Click" />

                    </FooterTemplate>

                    <ItemTemplate>

                        <asp:DropDownList
                            ID="DropDownList1"
                            DataSourceID="SqlDataSource3"
                            DataTextField="ContactTitle"
                            DataValueField="ContactTitle"
                            SelectedValue= '<%# Bind("ContactTitle") %>'
                            runat="server">

                        </asp:DropDownList>

                        <asp:SqlDataSource
                            ID="SqlDataSource3"
                            ConnectionString="<%$ ConnectionStrings:Northwind %>"
                            SelectCommand="select distintc ContactTitle from Customers"
                            runat="server">
                        </asp:SqlDataSource>

                    </ItemTemplate>

                </asp:TemplateField>   
            </Columns>

        </asp:GridView>

        <asp:SqlDataSource
            ID="SqlDataSource1"
            ConnectionString="<%$ ConnectionStrings:Northwind %>"
            SelectCommand="select CustomerID, CompanyName, ContactTitle from Customers"
            DeleteCommand="delete from Customers where CustomerID = @CustomerID"
            InsertCommand="insert into Customers (CustomerID, CompanyName, ContactTitle) values (@CustomerID, @CompanyName, @ContactTitle)"
            runat="server">

            <DeleteParameters>
                <asp:Parameter Type="String" Name="CustomerID" />
            </DeleteParameters>

            <InsertParameters>
                <asp:Parameter Type="String" Name="CustomerID" />
                <asp:Parameter Type="String" Name="CompanyName" />
                <asp:Parameter Type="String" Name="ContactTitle" />
            </InsertParameters>

        </asp:SqlDataSource>
    </div>
    </form>
</body>
</html>
