//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace example01
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VientoNorteEntities : DbContext
    {
        public VientoNorteEntities()
            : base("name=VientoNorteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClientesSet> ClientesSet { get; set; }
        public virtual DbSet<PedidosSet> PedidosSet { get; set; }
        public virtual DbSet<ProductosSet> ProductosSet { get; set; }
    }
}
