<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="WebForm3.aspx.cs" Inherits="example01.WebForm3" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <asp:DropDownList
            ID="DropDownList1"
            runat="server"
            AutoPostBack="true">
            <asp:ListItem Text="Selecciona el rol" Value="0"></asp:ListItem>
            <asp:ListItem Text="Usuario" Value="1"></asp:ListItem>
            <asp:ListItem Text="Administrador" Value="2"></asp:ListItem>
        </asp:DropDownList>
        <asp:SqlDataSource
            ID="SqlDataSource1"
            SelectCommand="select dbo.[Order Details].OrderId, Products.ProductName, dbo.[Order Details].UnitPrice, dbo.[Order Details].Quantity, dbo.[Order Details].Discount, Products.Discontinued from dbo.[Order Details] inner join Products on dbo.[Order Details].ProductId = dbo.[Products].ProductId"
            DeleteCommand="delete from dbo.[Order Details] where dbo.[Order Details].OrderId = @OrderId; delete fom dbo.[Orders] where dbo.[Orders].OrderId = @OrderId"
            OnDeleting="SqlDataSource1_Deleting"
            OnDeleted="SqlDataSource1_Deleted"
            runat="server" />
        <asp:GridView
            ID="GridView1"
            DataSourceID="SqlDataSource1"
            DataKeyNames="OrderId"
            AutoGenerateColumns="false"
            AutoGenerateEditButton="true"
            AllowCustomPaging="true"
            AutoGenerateDeleteButton="true"
            OnRowCommand="GridView1_RowCommand"
            runat="server">
            <Columns>
                <asp:BoundField DataField="ProductName" HeaderText="Nombre Producto" />
                <asp:BoundField DataField="UnitPrice" HeaderText="Precio" />
                <asp:BoundField DataField="Quantity" HeaderText="Cantidad" />
                <asp:CheckBoxField DataField="Discontinued" HeaderText="Descuento" />
                <asp:ButtonField ButtonType="Link" CommandName="Seleccionar_Index" Text="Seleccionar" />
            </Columns>            
        </asp:GridView>
        <asp:Label
            ID="Label1"        
            runat="server"
            Visible="false"
            ForeColor="Red">
        </asp:Label>
    </div>
    </form>
</body>
</html>
