<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="WebForm2.aspx.cs" Inherits="example01.WebForm2" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <asp:GridView
            ID="GridView1"
            runat="server"
            DataSourceID="SqlDataSource1"
            AutoGenerateColumns="true"
            AutoGenerateDeleteButton="true"
            AutoGenerateEditButton="true"
            DataKeyNames="CustomerID"></asp:GridView>
        <asp:SqlDataSource
            ID="SqlDataSource1"
            runat="server"
            ConnectionString="<%$ ConnectionStrings:Northwind %>"
            SelectCommand="select CustomerID, CompanyName, Address, City, PostalCode  from Customers"
            UpdateCommand="update Customers set CompanyName = @CompanyName, Address = @Address, PostalCode = @PostalCode where CustomerID = @CustomerID"
            OnUpdated="SqlDataSource1_Updated"
            OnUpdating=""
            DeleteCommand="Delete from Customers where CustomerID = @CustomerID"></asp:SqlDataSource>   
    </div>
    </form>
</body>
</html>
